import { expect, test } from "@playwright/test";
import { readFile } from "node:fs/promises";

test("BYOK fixture: import + paste, cross-document graph, report, backup and session privacy", async ({ page }, testInfo) => {
  test.setTimeout(120_000);
  await page.emulateMedia({ reducedMotion: "reduce" });
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  let extractionCalls = 0;
  let reportCalls = 0;
  const unexpected: string[] = [];
  await page.route("https://**/*", async route => {
    if (route.request().url() !== "https://ai-fixture.invalid/v1/chat/completions") { unexpected.push(route.request().url()); return route.abort(); }
    const body = route.request().postDataJSON();
    const prompt = body.messages[1].content as string;
    if (prompt.includes("STUDY_DATA_JSON")) {
      reportCalls++;
      return route.fulfill({ json: { choices: [{ message: { content: "# 合同学习报告\n\n## 星系要点\n合同订立与履行构成学习主线。[S1][S2]\n\n## 复习问题\n如何区分订立与履行？\n\n## 待核实\n请对照原文核查 AI 推断。" } }] } });
    }
    extractionCalls++;
    const existingText = prompt.match(/<EXISTING_CONCEPTS_JSON>\s*([\s\S]*?)\s*<\/EXISTING_CONCEPTS_JSON>/)?.[1];
    const existing = existingText ? JSON.parse(existingText) as {id:string;title:string}[] : [];
    const concepts = [{ title: "合同", type: "principle", system: "civil", importance: 80, confidence: 70, summary: "关于合同的学习概念", keyPoints: ["双方约定"] }, { title: extractionCalls === 1 ? "合同订立" : "违约责任", type: "principle", system: "civil", importance: 75, summary: "学习笔记中的概念", keyPoints: ["需要结合原文"] }];
    const relations: object[] = [{ source: concepts[0].title, target: concepts[1].title, type: "适用", strength: 80, citation: "本资料第一段（测试 fixture）" }];
    if (existing.length) relations.push({ source: concepts[1].title, target: existing[0].title, targetConceptId: existing[0].id, type: "解释", strength: 70, citation: "与先前资料中的合同概念关联（测试推断）" });
    return route.fulfill({ json: { choices: [{ message: { content: JSON.stringify({ concepts, relations }) } }] } });
  });
  await page.goto("/", { waitUntil: "domcontentloaded" });
  const root = page.getByTestId("law-universe-page");
  await expect(root).toBeVisible();
  const onboarding = page.getByRole("button", { name: "关闭引导" });
  await expect(onboarding).toBeVisible(); await onboarding.click();
  await page.getByTestId("law-universe-hud-workbench").click();
  const panel = page.getByTestId("law-universe-workbench");
  await expect(panel).toHaveAttribute("aria-busy", "false", { timeout: 30_000 });
  await expect(panel.getByLabel("Base URL", { exact: true })).toBeVisible();
  await panel.getByLabel("Base URL", { exact: true }).fill("https://ai-fixture.invalid/v1");
  await panel.getByLabel("API Key", { exact: true }).fill("fixture-session-key-not-real");
  await panel.getByLabel("Model", { exact: true }).fill("fixture-model");
  await panel.getByRole("button", { name: "保存设置" }).click();
  await page.getByTestId("law-universe-workbench-file-input").setInputFiles({ name: "合同订立.md", mimeType: "text/markdown", buffer: Buffer.from("教学示例，非法律意见。合同订立涉及要约与承诺，请整理为学习概念。") });
  await panel.getByLabel("资料标题", { exact: true }).fill("履行笔记");
  await panel.getByLabel("粘贴法律学习资料").fill("教学示例：合同履行与违约责任。请与前一份合同订立笔记联系起来复习。");
  await panel.getByRole("button", { name: "保存粘贴资料" }).click();
  const analyze = panel.getByRole("button", { name: "分析待处理资料（2）" });
  await expect(analyze).toBeEnabled();
  expect(extractionCalls).toBe(0);
  await analyze.click();
  await expect(panel.getByRole("region", { name: "资料分析" }).getByRole("status")).toContainText("本次完成 2/2", { timeout: 30_000 });
  await expect(root).toHaveAttribute("data-user-satellite-count", "4");
  await expect(root).toHaveAttribute("data-user-relation-count", "3");
  expect(extractionCalls).toBe(2);
  await panel.getByRole("button", { name: "生成学习报告" }).click();
  await expect(page.getByTestId("study-report")).toContainText("合同学习报告");
  expect(reportCalls).toBe(1);
  const downloadReport = page.waitForEvent("download");
  await panel.getByRole("button", { name: "下载 Markdown" }).click();
  const reportFile = await downloadReport;
  const reportText = await readFile((await reportFile.path())!, "utf8");
  expect(reportText).toContain("合同订立.md"); expect(reportText).toContain("履行笔记.txt");
  expect(reportText).not.toContain("fixture-session-key-not-real");
  await panel.getByRole("button", { name: "数据备份" }).click();
  const downloadBackup = page.waitForEvent("download");
  await page.getByRole("button", { name: "导出为 JSON 文件" }).click();
  const backupFile = await downloadBackup;
  const backupText = await readFile((await backupFile.path())!, "utf8");
  expect(backupText).not.toContain("fixture-session-key-not-real");
  expect(JSON.parse(backupText).data.sourceDocs).toHaveLength(2);
  await page.getByRole("button", { name: "关闭数据备份面板" }).click();
  await panel.getByRole("button", { name: "关闭工作台" }).click();
  await expect(root).toHaveAttribute("data-user-satellite-count", "4");
  await page.screenshot({ path: testInfo.outputPath("learning-galaxy.png") });
  await page.reload({ waitUntil: "domcontentloaded" });
  await expect(root).toHaveAttribute("data-user-satellite-count", "4");
  await page.getByTestId("law-universe-hud-workbench").click();
  await expect(panel).toHaveAttribute("aria-busy", "false", { timeout: 30_000 });
  await expect(panel.getByLabel("API Key", { exact: true })).toHaveValue("");
  await expect(panel.getByLabel("Base URL", { exact: true })).toHaveValue("https://ai-fixture.invalid/v1");
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
  expect(overflow).toBe(false);
  await page.screenshot({ path: testInfo.outputPath("learning-workbench.png") });
  expect(errors).toEqual([]);
  expect(unexpected).toEqual([]);
});
